data:
  raw1: "../data/raw/2018.csv"
  raw2: "../data/raw/airlines.csv"
  raw3: "../data/raw/airports.csv"
  clean1: "../data/cleaned/clean_flight_delays_cancellations.csv"
  clean2: "../data/cleaned/clean_airlines.csv"
  clean3: "../data/cleaned/clean_airports.csv"
  clean4: "../data/cleaned/clean_flights.csv"
  plot1: "../data/plot/day_of_week.csv"
  plot2: "../data/plot/airline.csv"
  plot3: "../data/plot/airport.csv"
  plot4: "../data/plot/state.csv"
  plot5: "../data/plot/diversion.csv"
  plot6: "../data/plot/time_wheels_arrival.csv"
  plot7: "../data/plot/freq_per_day.csv"
  plot8: "../data/plot/freq_per_airline.csv"
  plot9: "../data/plot/freq_per_airport.csv"
  plot10: "../data/plot/freq_per_state.csv"
  plot11: "../data/plot/freq_per_dest.csv"